### ISSUE TITLE
CHTC workflow may be deleting metadata lines

### ISSUE THREAD

**Issue by cmgtam** [uw-cmg/MAST#449]
CHTC DAGman workflow may be deleting metadata lines, and also fails with no directory detected for POSCAR file (possibly because of deleting metadata lines)...? 
Needs investigation.

**Comment by cmgtam** [comment]
Example: 
$ cat ~/testing_MAST/SCRATCH/test_1000/neb_o18-o17_q\=p2_opt1/PRE_script_output 
Thu May  5 14:01:11 CDT 2016
Parse arguments.
RECIPE: //home/.../testing_MAST/SCRATCH/test_1000
ING: neb_o18-o17_q=p2_opt1
Changing value of structure, structure.
Traceback (most recent call last):
  File "//mnt/gluster/.../MAST/submit/platforms/chtc_dagman/mast_do_setup_python.py", line 44, in <module>
    returncode = main()
  File "//mnt/gluster/.../MAST/submit/platforms/chtc_dagman/mast_do_setup_python.py", line 38, in main
    my_recipe_plan = mymon.set_up_recipe_plan(recipe_name, 1)
  File "//mnt/gluster/.../MAST/controllers/mastmon.py", line 72, in set_up_recipe_plan
    recipe_plan_obj = rsetup.start()
  File "//mnt/gluster/.../MAST/recipe/recipesetup.py", line 305, in start
    recipe_plan = self.create_recipe_plan()
  File "//mnt/gluster/.../MAST/recipe/recipesetup.py", line 193, in create_recipe_plan
    self.update_top_meta_for_ingred(ingred)
  File "//mnt/gluster/.../MAST/recipe/recipesetup.py", line 263, in update_top_meta_for_ingred
    self.metafile.write_data(myingred, data, 1)
  File "//mnt/gluster/.../MAST/utility/metadata.py", line 45, in write_data
    self.clear_data(keyword)
  File "//mnt/gluster/.../MAST/utility/metadata.py", line 96, in clear_data
    self.write_data(keyword, data.strip())
  File "//mnt/gluster/.../MAST/utility/metadata.py", line 34, in write_data
    self.clear_data(keyword)
  File "//mnt/gluster/.../MAST/utility/metadata.py", line 96, in clear_data
    self.write_data(keyword, data.strip())
  File "//mnt/gluster/.../MAST/utility/metadata.py", line 33, in write_data
    entry += '; %s' % data
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
NEB detected; switching submission script

**Comment by cmgtam** [comment]
This issue is difficult to reproduce. It occurs if the top metadata file is corrupted by not having the ingredient name. I think that this can happen after a crash. There may be some issues with the clear_data function, as apparently that function empties the file and rewrites all lines except the specified line. clear_data is called before each write in the metafile.

It seems unstable to keep rewriting the metafile. Maybe add an if statement prior to self.update_top_meta_for_ingred?

**Comment by cmgtam** [comment]
Test appears to repair broken workflow on CHTC.
